name    'ft-public_brands_api'
version '0.0.0'
source 'git@github.com:Financial-Times/public-brands-api.git'
author 'ft'
license 'Apache License, Version 2.0'
summary ''
description 'Brands Public API'
project_page 'https://github.com/Financial-Times/public-brands-api'

## Add dependencies, if any:
dependency 'ft/go_service_profile', '>= 0.0.0'
